name: Construir
on:
  push:
    branches:
      - development

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Clones superficiais devem ser desabilitados para uma melhor análise

      # Passo para configurar a versão correta do Java
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      # Passo para compilar o projeto usando Maven
      - name: Build with Maven
        run: mvn clean install

      # Passo para realizar a análise no SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Para obter informações de PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
